### ISSUE TITLE
Patents?

### ISSUE THREAD

**Issue by dalbert2** [kmackay/micro-ecc#93]
Has anyone looked into whether using micro-ECC would cause an application to infringe on the [Certicom patents](https://en.wikipedia.org/wiki/ECC_patents)?

**Comment by jbdatko** [comment]
IANAL and probably you need a lawyer to give you counsel re: anything with patents, but you might find this useful: https://www.rfc-editor.org/rfc/rfc6090.txt

**Comment by kmackay** [comment]
You should check with a lawyer; I can't make any guarantees about patent infringement.

**Comment by kmackay** [comment]
I don't know of any unexpired patents covering the micro-ecc code though.

**Comment by dalbert2** [comment]
Thank you...and thank you again for micro-ecc!

**Comment by weiqj** [comment]
What about point compression? I still avoid it in my products because I
have concerns.
Appreciate your effort very much.

Best
Qingjun

On May 21, 2017 1:36 PM, "Ken MacKay" <notifications@github.com> wrote:

I don't know of any unexpired patents covering the micro-ecc code though.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kmackay/micro-ecc/issues/93#issuecomment-302951051>,
or mute
the thread

**Comment by msembinelli** [comment]
As per weiqj's comment, I am also curious. Here is the patent in question:
https://www.google.com/patents/US6252960

It expires in August 2018
